/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const group = useRef()
  useFrame((state, delta) => (group.current.rotation.y += 0.01))

  const { nodes, materials } = useGLTF('/meDesk.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale="0.07" position={[0, 1, 0]}>
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials['Material.006']} />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0, 0, -9.99]}
        scale={[8.27, 8.27, 1]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[0, -19.92, 28.13]}
        scale={1.45}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[2.56, -18.03, 18.48]}
        scale={[5.91, 0.45, 2.26]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-8.32, -17.93, 18.48]}
        scale={[1.5, 0.55, 2.26]}
      />
      <group position={[-12.16, -18.03, 31.5]} rotation={[0, -0.47, 0]} scale={[5.91, 0.45, 2.26]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={nodes.Cube006_1.material} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.002']} />
      </group>
      <group position={[6.15, -4.75, 35.07]} scale={[-12.47, -7.03, 0.55]}>
        <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube007_4.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube007_5.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube007_6.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube007_7.geometry} material={materials['Material.015']} />
      </group>
    </group>
  )
}

useGLTF.preload('/meDesk.gltf')
